services:
  divasalonapi:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
